---
- hosts: 172.31.12.40
  become: true
  tasks:
    - name: deploy project2 docker container
      command: docker stop --name project2
      command: docker rm --name project2
      command: sleep 15
      command: docker run -d --name project2 -p 8080:80 sreeramakumar/project2:latest
