---
- name: docker image build and push to docker hub
  hosts: all
  gather_facts: no
  become: yes
  tasks:
  - name: Create docker images using war artifactory
    command: docker build -t project2:latest /var/lib/jenkins/workspace/project2


  - name: create tag to image
    command: docker tag project2:latest ravindra226/devopsproject2:latest
    
  - name: docker hub login
    command: docker login --username ravindra226 --password Davi@1228

  - name: push image to docker hub
    command: docker push ravindra226/devopsproject2:latest

  - name: remove docker image from docker server server post image push
    command: docker rmi project2:latest ravindra226/devopsproject2:latest
    ignore_errors: yes
